package http

import (
	"net/http"
	"time"

	"github.com/entorno35/backend/internal/core/services"
	"github.com/entorno35/backend/internal/domain"
	"github.com/entorno35/backend/internal/middleware"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// AssessmentHandler handles assessment-related HTTP requests
type AssessmentHandler struct {
	assessmentService *services.AssessmentService
}

// NewAssessmentHandler creates a new assessment handler
func NewAssessmentHandler(assessmentService *services.AssessmentService) *AssessmentHandler {
	return &AssessmentHandler{
		assessmentService: assessmentService,
	}
}

// CreateAssessmentRequest represents the request body for creating an assessment
type CreateAssessmentRequest struct {
	StaffID uuid.UUID `json:"staff_id" binding:"required"`
	Period  int       `json:"period" binding:"required"`
}

// CreateAssessmentResponse represents the response for creating an assessment
type CreateAssessmentResponse struct {
	ID        uuid.UUID           `json:"id"`
	StaffID   uuid.UUID           `json:"staff_id"`
	CompanyID uuid.UUID           `json:"company_id"`
	Period    int                 `json:"period"`
	GuideType domain.GuideType    `json:"guide_type"`
	Status    domain.AssessmentStatus `json:"status"`
	CreatedAt string              `json:"created_at"`
}

// CreateAssessment creates a new assessment
// POST /api/v1/assessments
func (h *AssessmentHandler) CreateAssessment(c *gin.Context) {
	companyID, ok := middleware.RequireCompanyID(c)
	if !ok {
		return // Already aborted with error
	}

	var req CreateAssessmentRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Verify staff belongs to company (should be handled by service/repository)
	assessment, err := h.assessmentService.CreateAssessment(
		services.CreateAssessmentRequest{
			StaffID: req.StaffID,
			Period:  req.Period,
		},
		companyID,
	)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusCreated, CreateAssessmentResponse{
		ID:        assessment.ID,
		StaffID:   assessment.StaffID,
		CompanyID: assessment.CompanyID,
		Period:    assessment.Period,
		GuideType: assessment.GuideType,
		Status:    assessment.Status,
		CreatedAt: assessment.CreatedAt.Format(time.RFC3339),
	})
}

// GetAssessment retrieves an assessment by ID
// GET /api/v1/assessments/:id
func (h *AssessmentHandler) GetAssessment(c *gin.Context) {
	companyID, ok := middleware.RequireCompanyID(c)
	if !ok {
		return
	}

	assessmentIDStr := c.Param("id")
	assessmentID, err := uuid.Parse(assessmentIDStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid assessment ID"})
		return
	}

	assessment, err := h.assessmentService.GetAssessment(assessmentID, companyID)
	if err != nil {
		if err.Error() == "failed to fetch assessment: assessment not found" {
			c.JSON(http.StatusNotFound, gin.H{"error": "assessment not found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, assessment)
}

// ListAssessmentsRequest represents query parameters for listing assessments
type ListAssessmentsRequest struct {
	StaffID *uuid.UUID            `form:"staff_id"`
	Period  *int                  `form:"period"`
	Status  *domain.AssessmentStatus `form:"status"`
}

// ListAssessments retrieves assessments with optional filters
// GET /api/v1/assessments
func (h *AssessmentHandler) ListAssessments(c *gin.Context) {
	companyID, ok := middleware.RequireCompanyID(c)
	if !ok {
		return
	}

	var req ListAssessmentsRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	assessments, err := h.assessmentService.ListAssessments(companyID, req.StaffID, req.Period, req.Status)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, assessments)
}

// CreateAssessmentLinkRequest represents the request body for creating an assessment link
type CreateAssessmentLinkRequest struct {
	ExpiresInDays int `json:"expires_in_days" binding:"required,min=1,max=365"`
}

// CreateAssessmentLinkResponse represents the response for creating an assessment link
type CreateAssessmentLinkResponse struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Link      string    `json:"link"` // Full URL (to be generated by frontend or service)
}

// CreateAssessmentLink creates a secure link for an assessment
// POST /api/v1/assessments/:id/links
func (h *AssessmentHandler) CreateAssessmentLink(c *gin.Context) {
	assessmentIDStr := c.Param("id")
	assessmentID, err := uuid.Parse(assessmentIDStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid assessment ID"})
		return
	}

	staffID, ok := middleware.RequireStaffID(c)
	if !ok {
		return
	}

	var req CreateAssessmentLinkRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Use assessment ID from URL
	expiresIn := time.Duration(req.ExpiresInDays) * 24 * time.Hour

	link, err := h.assessmentService.CreateAssessmentLink(
		services.CreateAssessmentLinkRequest{
			AssessmentID: assessmentID,
			ExpiresIn:    expiresIn,
		},
		staffID,
	)
	if err != nil {
		if err.Error() == "assessment does not belong to staff member" {
			c.JSON(http.StatusForbidden, gin.H{"error": err.Error()})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusCreated, CreateAssessmentLinkResponse{
		Token:     link.Token,
		ExpiresAt: link.ExpiresAt,
		Link:      "", // Frontend will construct the full URL
	})
}

